# Site settings
title: Ekaksh Kataria
description: Personal website / Portfolio
baseurl: ""
url: "" 

# Build settings
markdown: kramdown
permalink: /:title/
plugins:
  - jekyll-feed
  - jekyll-seo-tag


collections:
  projects:
    output: true
    permalink: /:collection/:name/

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "page"
  - scope:
      path: ""
    values:
      layout: "default"

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .gitignore
  - README.md
  - structure.txt